import xsane-0.992.tar.gz

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -846,6 +846,7 @@ Optional Features:
   --disable-jpeg          do not include JPEG support
   --disable-png           do not include PNG support
   --disable-tiff          do not include TIFF support
+  --disable-lcms          do not include LCMS support
   --disable-nls           do not use Native Language Support
   --disable-sanetest      Do not try to compile and run a test SANE program
   --disable-gimptest      do not try to compile and run a test GIMP program
@@ -1321,14 +1322,14 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 # version code:
 V_MAJOR=0
-V_MINOR=991
+V_MINOR=992
 
 PACKAGE=xsane
 
 BINPROGS="xsane"
 
 # languages
-ALL_LINGUAS="cs da de es fr hu it ja nl pl pt pt_BR ro ru sk sl sr sv vi tr zh"
+ALL_LINGUAS="ca cs da de es fr hu it ja nl pl pt pt_BR ro ru sk sl sr sv vi tr zh zh_CN"
 
 SANE_V_MAJOR=1
 VERSION=${V_MAJOR}.${V_MINOR}
@@ -1432,6 +1433,18 @@ else
 fi;
 echo "$as_me:$LINENO: result: $USE_TIFF" >&5
 echo "${ECHO_T}$USE_TIFF" >&6
+
+echo "$as_me:$LINENO: checking whether LCMS (color management) support is requested" >&5
+echo $ECHO_N "checking whether LCMS (color management) support is requested... $ECHO_C" >&6
+# Check whether --enable-lcms or --disable-lcms was given.
+if test "${enable_lcms+set}" = set; then
+  enableval="$enable_lcms"
+  USE_LCMS=$enableval
+else
+  USE_LCMS=yes
+fi;
+echo "$as_me:$LINENO: result: $USE_LCMS" >&5
+echo "${ECHO_T}$USE_LCMS" >&6
 
 echo ""
 echo "**************************************************************************"
@@ -5785,6 +5798,83 @@ if test $ac_cv_lib_tiff_TIFFOpen = yes; then
 _ACEOF
 
   LIBS="-ltiff $LIBS"
+
+fi
+
+fi
+
+if test "${USE_LCMS}" = "yes"; then
+
+echo "$as_me:$LINENO: checking for cmsOpenProfileFromFile in -llcms" >&5
+echo $ECHO_N "checking for cmsOpenProfileFromFile in -llcms... $ECHO_C" >&6
+if test "${ac_cv_lib_lcms_cmsOpenProfileFromFile+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llcms  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char cmsOpenProfileFromFile ();
+int
+main ()
+{
+cmsOpenProfileFromFile ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_lcms_cmsOpenProfileFromFile=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_lcms_cmsOpenProfileFromFile=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_lcms_cmsOpenProfileFromFile" >&5
+echo "${ECHO_T}$ac_cv_lib_lcms_cmsOpenProfileFromFile" >&6
+if test $ac_cv_lib_lcms_cmsOpenProfileFromFile = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBLCMS 1
+_ACEOF
+
+  LIBS="-llcms $LIBS"
 
 fi
 
@@ -12505,6 +12595,12 @@ if test "${ac_cv_lib_png_png_create_info_struct}" = "yes"; then
   echo "* - PNG  support activated                                     *"
 else
   echo "* - PNG  support deactivated                                   *"
+fi
+
+if test "${ac_cv_lib_lcms_cmsOpenProfileFromFile}" = "yes"; then
+  echo "* - LCMS (color management) support activated                  *"
+else
+  echo "* - LCMS (color management) support deactivated                *"
 fi
 
 echo "*                                                              *"
